### ISSUE TITLE
This integration is private. Only the application owner can add it.

### ISSUE THREAD

**Issue by YinYin-Falcon** [tippf3hlr/game-roles-v2#13]

**Comment by tippfehlr** [comment]
Then you are propably trying to invite my testing bot... Where did you get the link? [This](https://discord.com/api/oauth2/authorize?client_id=813130993640013874&permissions=8&scope=bot) is the correct one.

**Comment by YinYin-Falcon** [comment]
over here: https://top.gg/bot/813130993640013874

but my history shows it had a different id before, which no longer exists

**Comment by tippfehlr** [comment]
On accident I left the wrong invite link there, now I updated it to show the correct one. Thanks!
