### ISSUE TITLE
Activity Role only requires playing/listening etc.

### ISSUE THREAD

**Issue by tippfehlr** [tippf3hlr/game-roles-v2#43]
as per Hugo Moreira#4306
https://discord.com/channels/958393035543175258/958393035543175261/1051125688515711086

**Comment by tippfehlr** [comment]
name: status role

**Comment by tippfehlr** [comment]
UI: /statusrrole <status> <role>
Running without args shows current status roles.

Status roles are always temporary.

**Comment by tippfehlr** [comment]
also add screenshare as requested by Daksh#0001

**Comment by tippfehlr** [comment]
also requested by deflanco

**Comment by DeFlanko** [comment]
> also requested by deflanko

thats me!
